version: '3'
services:
  app:
    image: blaxsior/cicd-test-app
    ports: 
      - "80:80"
    env_file:
      - "./.env"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s