# https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
name: CD
on:
  workflow_run: 
    workflows: ['CI']
    types: completed
  workflow_dispatch:
# https://docs.github.com/en/actions/learn-github-actions/expressions#format
jobs:
  setup:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # deploy 파일 보내야 함
      - name: .env 파일 생성
        run: |
          echo "SECRET_KEY1=$SECRET_VALUE1" >> .env
          echo "SECRET_KEY2=$SECRET_VALUE2" >> .env
          echo "LISTEN_PORT=$LISTEN_PORT" >> .env
          echo "NODE_ENV=production" >> .env
      
      - name: 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USER}}
          port: ${{secrets.AWS_PORT}}
          key: ${{secrets.AWS_KEY}}
          source: "./.env, ./docker-compose.prod.yml"
      - name: ssh 기반 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USER}}
          port: ${{secrets.AWS_PORT}}
          key: ${{secrets.AWS_KEY}}
          script: |
            docker compose -f docker-compose.prod.yml stop
            docker compose -f docker-compose.prod.yml up -d --build