name: my-github-action2(github-checkout)
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  repository_dispatch:
jobs:
  # job_name
  build:
    name: chekcout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run echo hello
        run: echo hello world
      - name: Run pwd
        run: pwd
      - name: Run ls -al
        run: ls -al
      - name: cat index.html
        run: cat ./index.html
        # 이걸로 환경 정보 복사 가능
      - name: generate .env file
        run: |
          echo "SECRET_KEY1=$SECRET_VALUE1" >> .env
          echo "SECRET_KEY2=$SECRET_VALUE2" >> .env
        env:
          SECRET_VALUE1: ${{ secrets.SECRET_KEY1 }}
          SECRET_VALUE2: ${{ secrets.SECRET_KEY2 }}
          # do not this in production environment!
      - name: cat .env file
        run: cat ./.env
      - name: echo bracket
        run: echo ${SECRET_VALUE1}hello
